Repository k8snetworkplumbingwg/kubemacpool, pull requests merged in 2020-05, with the labels that each got.

#127 Bump CNAO
  cluster/up.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#126 Bump kubevirtci
  cluster/kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#132 Add PR/Issues templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#131 Remove 1.17.0 provider reference
  automation/check-patch.e2e-k8s.sh
  cluster/kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#133 Replace multistage build by vendored golang
  .travis.yml
  Dockerfile
  Makefile
  automation/check-patch.e2e-k8s.sh
  build/.dockerignore
  build/Dockerfile
  cluster/sync.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#128 Add opt in functionality
  config/default/manager/manager.yaml
  config/default/rbac/rbac_role.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
  pkg/controller/pod/pod_controller.go
  pkg/controller/virtualmachine/virtualmachine_controller.go
  pkg/pool-manager/pod_pool.go
  pkg/pool-manager/pool.go
  pkg/pool-manager/virtualmachine_pool.go
  tests/pods_test.go
  tests/tests.go
  tests/virtual_machines_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#129 adding proper documentation to operate kubemacpool opt-in new behavior
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#135 DNF remove connection-refuse ignore in pod e2e tests
  tests/pods_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#136 adding check that all genereated files are commited before performing automation tests
  .travis.yml
  Makefile
  hack/check.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#138 Remove Pending flag from skipped tests
  tests/virtual_machines_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#130 Enable cluster-sync with external provider
  .gitignore
  Makefile
  README.md
  cluster/clean.sh
  cluster/sync.sh
  cluster/up.sh
  config/test/kustomization.yaml
  config/test/manager_image_patch.yaml
  hack/clean-ns-finalizers.sh
  hack/functest.sh
  hack/run.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#139 Bump Kubevirt to v0.29.0
  cluster/up.sh
  go.mod
  go.sum
  tests/virtual_machines_test.go
  vendor/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  vendor/kubevirt.io/client-go/api/v1/openapi_generated.go
  vendor/kubevirt.io/client-go/api/v1/schema.go
  vendor/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  vendor/kubevirt.io/client-go/api/v1/types.go
  vendor/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  vendor/kubevirt.io/kubevirt/tools/vms-generator/utils/BUILD.bazel
  vendor/kubevirt.io/kubevirt/tools/vms-generator/utils/utils.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#137 adding documentation as to how to enable/disable opt-in of kubemacpool in a namespace
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#144 Bump kube-admission-webhook 0.7.0
  go.mod
  go.sum
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/secret.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#146 oath of a contributor
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#147 Remove ownership stealing code
  pkg/manager/manager.go
  pkg/webhook/webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#149 Remove CSR's related RBAC
  config/default/rbac/rbac_role.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#145 Paramtereize manager namespaces used by functest
  README.md
  tests/tests.go
  tests/tests_suite_test.go
  tests/virtual_machines_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#150 Parameterize manager namespace at tests from pods
  README.md
  hack/clean-ns-finalizers.sh
  tests/tests.go
  tests/tests_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#151 Check manager pod readyness changing leadership at test
  tests/tests.go
  tests/virtual_machines_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#155 Bump golang to 1.13
  go.mod
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/golang.org/x/tools/internal/imports/mkindex.go
  vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#157 Change opt in label default value to allocate
  README.md
  config/default/manager/manager.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
  tests/pods_test.go
  tests/virtual_machines_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#159 adding retryOnConflict methods to protect from conflicts
  pkg/controller/virtualmachine/virtualmachine_controller.go
  pkg/pool-manager/virtualmachine_pool.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#156 Add junit and polarion test reporters
  Makefile
  automation/check-patch.e2e-k8s.sh
  go.mod
  go.sum
  hack/functest.sh
  tests/tests_suite_test.go
  vendor/kubevirt.io/qe-tools/LICENSE
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#152 add additional wait time in tests that check failed vm creation scenarios
  cmd/manager/main.go
  pkg/names/names.go
  tests/tests.go
  tests/virtual_machines_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#165 fix shell formatting of external cluster example
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
