Repository k8snetworkplumbingwg/kubemacpool, pull requests merged in 2020-06, with the labels that each got.

#164 Add polarion test_id flags
  automation/openshift.cnv.tier1.sh
  go.mod
  go.sum
  tests/virtual_machines_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#166 adding reconcile request id to better track multiple thread logs
  pkg/controller/virtualmachine/virtualmachine_controller.go
  pkg/pool-manager/pool_test.go
  pkg/pool-manager/virtualmachine_pool.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#169 remove disruption pod budget from kubemacpool
  config/default/manager/manager.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#171 Ubi8 minimal
  build/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#161 moving finalizer addition to webhook
  pkg/controller/virtualmachine/virtualmachine_controller.go
  pkg/pool-manager/virtualmachine_pool.go
  pkg/webhook/virtualmachine/virtualmachine.go
  tests/virtual_machines_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#168 Remove finalizer always
  pkg/controller/virtualmachine/virtualmachine_controller.go
  tests/virtual_machines_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#172 Remove builder Dockerfile and friends
  Makefile
  hack/docker-image/Dockerfile
  hack/docker-image/entrypoint.sh
  hack/docker-image/install.sh
  hack/docker/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#174 [release-v0.14.0] adding reconcile request id to better track multiple thread logs (#166)
  pkg/controller/virtualmachine/virtualmachine_controller.go
  pkg/pool-manager/pool_test.go
  pkg/pool-manager/virtualmachine_pool.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#160 aligning wait-time of test to those of production
  config/test/kubemacpool.yaml
  config/test/kustomization.yaml
  config/test/manager_image_patch.yaml
  hack/functest.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#180 Correct the kube-admission-webhook version at go.mod
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#184 Remove HEALT_PROBE_HOST and HEALT_PROBE_PORT
  config/default/manager/manager.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
  pkg/manager/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#183 add collision detection test in leader change context.
  tests/tests.go
  tests/virtual_machines_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#189 add logs to document failing scenarios in kubemacpool startup.
  cmd/manager/main.go
  pkg/manager/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#188 fix race between webhook and controller
  pkg/pool-manager/pool_test.go
  pkg/pool-manager/virtualmachine_pool.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#190 remove old leader labels after leader election has been won.
  pkg/manager/leaderelection.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#192 [Release v0.14.0] fix cache race
  pkg/pool-manager/pool_test.go
  pkg/pool-manager/virtualmachine_pool.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#195 [Release v0.14.0] change leadership mechanism
  cluster/sync.sh
  config/default/manager/manager.yaml
  config/default/rbac/rbac_role.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
  pkg/manager/leaderelection.go
  pkg/manager/manager.go
  pkg/names/names.go
  pkg/pool-manager/pool.go
  pkg/pool-manager/pool_test.go
  pkg/pool-manager/virtualmachine_pool.go
  tests/tests.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#196 remove debug print
  pkg/pool-manager/pool_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#199 [release-v0.14.0] aligning wait-time of test to those of production
  config/test/kubemacpool.yaml
  config/test/kustomization.yaml
  config/test/manager_image_patch.yaml
  hack/functest.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#201 Change deployment strategy to Recreate
  config/default/manager/manager.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#204 drop namespace annotations
  config/default/manager/manager.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
  pkg/pool-manager/pool_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#209 fix leadership label removed after twice winning election
  pkg/manager/leaderelection.go
  pkg/manager/manager_suite_test.go
  pkg/manager/manager_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#212 Update leader label only at pods with label 'app=kubemacpool'
  pkg/manager/leaderelection.go
  pkg/manager/manager_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
