Repository k8snetworkplumbingwg/kubemacpool, pull requests merged in 2020-07, with the labels that each got.

#215 Remove ginkgo cmd
  Makefile
  hack/functest.sh
  tools.go
  vendor/github.com/onsi/ginkgo/ginkgo/bootstrap_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/build_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/ginkgo_ast_nodes.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/import.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/package_rewriter.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/test_finder.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/testfile_rewriter.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/testing_t_rewriter.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/generate_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/help_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/interrupthandler/interrupt_handler.go
  vendor/github.com/onsi/ginkgo/ginkgo/interrupthandler/sigquit_swallower_unix.go
  vendor/github.com/onsi/ginkgo/ginkgo/interrupthandler/sigquit_swallower_windows.go
  vendor/github.com/onsi/ginkgo/ginkgo/main.go
  vendor/github.com/onsi/ginkgo/ginkgo/nodot/nodot.go
  vendor/github.com/onsi/ginkgo/ginkgo/nodot_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/notifications.go
  vendor/github.com/onsi/ginkgo/ginkgo/run_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/run_watch_and_build_command_flags.go
  vendor/github.com/onsi/ginkgo/ginkgo/suite_runner.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/build_args.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/build_args_old.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/log_writer.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/run_result.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/test_runner.go
  vendor/github.com/onsi/ginkgo/ginkgo/testsuite/test_suite.go
  vendor/github.com/onsi/ginkgo/ginkgo/testsuite/vendor_check_go15.go
  vendor/github.com/onsi/ginkgo/ginkgo/testsuite/vendor_check_go16.go
  vendor/github.com/onsi/ginkgo/ginkgo/unfocus_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/version_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/delta.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/delta_tracker.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/dependencies.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/package_hash.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/package_hashes.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/suite.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch_command.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#216 Add junit polarion reporter
  automation/check-patch.e2e-k8s.sh
  go.mod
  go.sum
  tests/tests_suite_test.go
  vendor/kubevirt.io/qe-tools/LICENSE
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XL

#214 Remove pod range change in tests
  config/test/kubemacpool.yaml
  config/test/kustomization.yaml
  config/test/manager_range_patch.yaml
  pkg/pool-manager/pool.go
  pkg/pool-manager/pool_test.go
  pkg/utils/utils.go
  pkg/utils/utils_suite_test.go
  pkg/utils/utils_test.go
  tests/pods_test.go
  tests/tests.go
  tests/virtual_machines_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#191 README: production user should change mac range
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#218 move to use latest z stream kubevirt release
  cluster/up.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#219 [release-v0.14.0] Backport kubevirt to latest z stable
  cluster/up.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#208 Bump kube-admission-webhook to 0.9.0
  go.mod
  go.sum
  pkg/webhook/webhook.go
  tests/certificates_test.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/client.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/configuration.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/controller.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/manager.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/secret.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/cert.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/pem.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/triple.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/secret.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/triple/cert.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/server.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#223 Bump qe-tools to 0.1.6
  go.mod
  go.sum
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#225 [release-v0.14.0] Bump qe-tools to 0.1.6
  go.mod
  go.sum
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#222 update damonsets to apps/v1 in manifests
  hack/cni-plugins/cni-plugins.yaml
  hack/multus/multus.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#227 Use a env var for polarion '--test-suite-params'
  hack/functest.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#230 waitToStartLeading goroutine does not catch error.
  pkg/manager/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#229 Kaw 0.10.0
  dnm
  go.mod
  go.sum
  pkg/webhook/webhook.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/cleanup.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/configuration.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/controller.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/manager.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/pem.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/server.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#231 separate label update in updateLeaderLabel
  pkg/manager/leaderelection.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#233 Bump kaw to 0.11.0
  go.mod
  go.sum
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/controller.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/secret.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#234 Kaw 0.12.0
  go.mod
  go.sum
  pkg/manager/manager.go
  pkg/webhook/webhook.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/cleanup.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/configuration.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/controller.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/manager.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/options.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/secret.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/server.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL
