Repository k8snetworkplumbingwg/kubemacpool, pull requests merged in 2021-04, with the labels that each got.

#279 Move cert-manager execution to a new pod
  cmd/manager/main.go
  config/default/kustomization.yaml
  config/default/manager/manager.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
  config/test/kustomization.yaml
  go.mod
  pkg/manager/manager.go
  pkg/names/names.go
  pkg/webhook/pod/pod.go
  pkg/webhook/virtualmachine/virtualmachine.go
  pkg/webhook/webhook.go
  tests/tests.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/server.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.gitignore
  vendor/sigs.k8s.io/controller-runtime/.golangci.yml
  vendor/sigs.k8s.io/controller-runtime/CONTRIBUTING.md
  vendor/sigs.k8s.io/controller-runtime/FAQ.md
  vendor/sigs.k8s.io/controller-runtime/Makefile
  vendor/sigs.k8s.io/controller-runtime/OWNERS
  vendor/sigs.k8s.io/controller-runtime/OWNERS_ALIASES
  vendor/sigs.k8s.io/controller-runtime/README.md
  vendor/sigs.k8s.io/controller-runtime/SECURITY_CONTACTS
  vendor/sigs.k8s.io/controller-runtime/TMP-LOGGING.md
  vendor/sigs.k8s.io/controller-runtime/VERSIONING.md
  vendor/sigs.k8s.io/controller-runtime/alias.go
  vendor/sigs.k8s.io/controller-runtime/code-of-conduct.md
  vendor/sigs.k8s.io/controller-runtime/doc.go
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/conversion/conversion.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/signals/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/signals/signal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/signals/signal_posix.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/signals/signal_windows.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/conversion.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/decoder.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#282 Reduce wait-time to 5 min
  config/default/manager/manager.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
  tests/virtual_machines_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#283 cluster-up, increase kubevirt timeout
  cluster/up.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#284 ci, add deployment print upon changeReplicas failure
  tests/tests.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#285 Remove "app" from matchingLabels
  config/default/kustomization.yaml
  config/default/manager/manager.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#286 Delete pods to restart KMP
  tests/tests.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#290 Bump kube-admission-webhook 0.15.0
  go.mod
  go.sum
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/manager.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/secret.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/cert.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/pem.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#291 bump cluster-up to follow kuvevirt v0.40
  cluster/up.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
