Repository k8snetworkplumbingwg/kubemacpool, pull requests merged in 2021-05, with the labels that each got.

#292 fix relaod if controller-manager.Start() returns
  pkg/manager/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#295 cluster-up, Bump CNAO version
  cluster/up.sh
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#297 [release-v0.21] initPodMap, Limit podList request to avoid memory max limit
  config/default/manager/manager.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
  pkg/pool-manager/pod_pool.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#300 initVirtualMachineMap, Limit vmList request to avoid memory max limit
  pkg/pool-manager/virtualmachine_pool.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#303 [release-v0.21] Revert pod pagination and limit removal
  config/default/manager/manager.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
  pkg/pool-manager/pod_pool.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#304 [release-v0.21] limit, Remove limit from kubemacpool deployment
  config/default/manager/manager.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#305 [release-v0.20] Remove kmp limits
  cluster/up.sh
  config/default/manager/manager.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#306 ci, upgrade to admissionregistration.v1 on certs tests
  tests/certificates_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#308 bump controller-tools to v0.5.0
  go.mod
  go.sum
  vendor/github.com/gobuffalo/flect/azure-pipelines.yml
  vendor/github.com/gobuffalo/flect/azure-tests.yml
  vendor/github.com/gobuffalo/flect/capitalize.go
  vendor/github.com/gobuffalo/flect/go.mod
  vendor/github.com/gobuffalo/flect/go.sum
  vendor/github.com/gobuffalo/flect/humanize.go
  vendor/github.com/gobuffalo/flect/ident.go
  vendor/github.com/gobuffalo/flect/plural_rules.go
  vendor/github.com/gobuffalo/flect/pluralize.go
  vendor/github.com/gobuffalo/flect/singularize.go
  vendor/github.com/gobuffalo/flect/underscore.go
  vendor/github.com/mattn/go-colorable/.travis.yml
  vendor/github.com/mattn/go-colorable/README.md
  vendor/github.com/mattn/go-colorable/colorable_appengine.go
  vendor/github.com/mattn/go-colorable/colorable_others.go
  vendor/github.com/mattn/go-colorable/colorable_windows.go
  vendor/github.com/mattn/go-colorable/go.mod
  vendor/github.com/mattn/go-colorable/go.sum
  vendor/github.com/mattn/go-colorable/go.test.sh
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-tools/pkg/crd/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/known_types.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/validation.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/schema.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/schema_visitor.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/spec.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/traverse.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/genall.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/errors.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/refs.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/parse.go
  vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/conv.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL
