Repository k8snetworkplumbingwg/kubemacpool, pull requests merged in 2021-08, with the labels that each got.

#322 metrics, Add kubevirt_kmp_duplicate_macs gauge
  config/default/manager/manager.yaml
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
  pkg/gauges/gauges.go
  pkg/pool-manager/virtualmachine_pool.go
  tests/kubectl/kubectl.go
  tests/virtual_machines_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L, release-note-none, ok-to-test

#326 dryRun, Fix logic conditions of dryRun
  pkg/webhook/pod/pod.go
  pkg/webhook/virtualmachine/virtualmachine.go
Labels: lgtm, approved

#328 tests, Create test vms and pods with shorter name
  tests/tests.go
Labels: lgtm, approved

#324 cluster-up, Bump CNAO and kubevirt to latest
  cluster/up.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved, release-note-none

#327 dryRun, Adapt VM Mac Address allocation to support dryRun
  pkg/controller/pod/pod_controller.go
  pkg/pool-manager/pod_pool.go
  pkg/pool-manager/pool_test.go
  pkg/pool-manager/virtualmachine_pool.go
  pkg/webhook/pod/pod.go
  pkg/webhook/virtualmachine/virtualmachine.go
  tests/virtual_machines_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L, release-note-none, ok-to-test
