Repository k8snetworkplumbingwg/kubemacpool, pull requests merged in 2022-03, with the labels that each got.

#358 vm-pool, Reject VMs with duplicate interfaces
  pkg/pool-manager/pool_test.go
  pkg/pool-manager/virtualmachine_pool.go
Labels: dco-signoff: yes, lgtm, approved, size/M, release-note

#363 config, Align kubemacpool manifest
  config/release/kubemacpool.yaml
  config/test/kubemacpool.yaml
Labels: dco-signoff: yes, lgtm, approved, release-note-none, size/M

#364 OWNERS, Add rhrazdil as reviewer
  OWNERS
Labels: dco-signoff: yes, size/XS, lgtm, approved, release-note-none

#365 unit tests: Add make check
  automation/check-patch.unit-test.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved, release-note-none

#361 webhook: Configure TLS Min Version and Cipher Suites using environment variables
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/webhook/pod/pod.go
  pkg/webhook/virtualmachine/virtualmachine.go
  pkg/webhook/webhook.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/cleanup.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/client.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/configuration.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/controller.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/manager.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/options.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/secret.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/cert.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/pem.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/triple.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/internal/httpserver/server.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/internal/metrics/metrics.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
Labels: dco-signoff: yes, size/XXL, lgtm, approved, release-note

#366 deps: Bump kaw to 0.20.0
  go.mod
  go.sum
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server.go
  vendor/modules.txt
Labels: bug, dco-signoff: yes, lgtm, approved, size/M, release-note
