Repository k8snetworkplumbingwg/kubemacpool, pull requests merged in 2024-12, with the labels that each got.

#443 docs: Remove VM Running API usage
  doc/simple-vm.yaml
  doc/vm-creation-example.md
Labels: dco-signoff: yes, size/XS, approved, release-note-none

#445 Makefile, push: Prevent overwriting existing version tags
  Makefile
Labels: dco-signoff: yes, lgtm, approved, release-note-none, size/S

#446 fmt: Fix LICENSE format
  pkg/gauges/gauges.go
  pkg/manager/manager.go
Labels: dco-signoff: yes, size/XS, lgtm, approved, release-note-none

#444 Add multi platform support
  Makefile
  build/Dockerfile
  hack/build-kubemacpool-docker.sh
  hack/build-kubemacpool-podman.sh
  hack/build-multiarch-kubemacpool.sh
  hack/init-buildx.sh
  hack/install-go.sh
Labels: dco-signoff: yes, lgtm, approved, size/L, release-note-none
