Repository k8snetworkplumbingwg/kubemacpool, pull requests merged in 2025-06, with the labels that each got.

#545 pod-pool: skip if pod has no multus network
  pkg/pool-manager/pod_pool.go
Labels: dco-signoff: yes, lgtm, approved, size/S, release-note

#547 pool-manager: Refactor full ip pool e2e tests to unit test
  config/test/kubemacpool.yaml
  config/test/kustomization.yaml
  config/test/manager_range_patch.yaml
  pkg/pool-manager/pool.go
  pkg/pool-manager/pool_test.go
  tests/virtual_machines_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L, release-note-none

#543 readme: Add content about metrics
  README.md
Labels: dco-signoff: yes, lgtm, approved, release-note-none, size/S
