Repository k8snetworkplumbingwg/kubemacpool, pull requests merged in 2025-03, with the labels that each got.

#456 feat: Add renovate config
  renovate.json
Labels: dco-signoff: yes, lgtm, approved, release-note-none, size/M

#467 renovate: Expand to all stable branches
  renovate.json
Labels: dco-signoff: yes, size/XS, lgtm, approved, release-note-none

#466 [release-0.44] vendor: Bump go1.22.11
  go.mod
Labels: dco-signoff: yes, size/XS, lgtm, approved, release-note-none

#491 renovate: Fix supported stable branches
  renovate.json
Labels: dco-signoff: yes, size/XS, lgtm, approved, release-note-none

#496 Revert "chore(deps): update module golang.org/x/oauth2 to v0.27.0 [se…
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/google.golang.org/appengine/LICENSE
  vendor/google.golang.org/appengine/internal/api.go
  vendor/google.golang.org/appengine/internal/api_classic.go
  vendor/google.golang.org/appengine/internal/api_common.go
  vendor/google.golang.org/appengine/internal/app_id.go
  vendor/google.golang.org/appengine/internal/base/api_base.pb.go
  vendor/google.golang.org/appengine/internal/base/api_base.proto
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
  vendor/google.golang.org/appengine/internal/identity.go
  vendor/google.golang.org/appengine/internal/identity_classic.go
  vendor/google.golang.org/appengine/internal/identity_flex.go
  vendor/google.golang.org/appengine/internal/identity_vm.go
  vendor/google.golang.org/appengine/internal/internal.go
  vendor/google.golang.org/appengine/internal/log/log_service.pb.go
  vendor/google.golang.org/appengine/internal/log/log_service.proto
  vendor/google.golang.org/appengine/internal/main.go
  vendor/google.golang.org/appengine/internal/main_common.go
  vendor/google.golang.org/appengine/internal/main_vm.go
  vendor/google.golang.org/appengine/internal/metadata.go
  vendor/google.golang.org/appengine/internal/net.go
  vendor/google.golang.org/appengine/internal/regen.sh
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
  vendor/google.golang.org/appengine/internal/transaction.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
  vendor/google.golang.org/appengine/urlfetch/urlfetch.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, lgtm, approved, release-note-none

#497 cluster/up: Maximize kubevirt releases pagination per page
  cluster/up.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved, release-note-none

#506 [release-0.42] go.mod, Makefile: Set go version to 1.20
  Makefile
  go.mod
Labels: dco-signoff: yes, size/XS, lgtm, approved, release-note-none

#505 [release-0.41] go.mod, Makefile: Set go version to 1.20
  Makefile
  go.mod
Labels: dco-signoff: yes, size/XS, lgtm, approved, release-note-none

#454 e2e: Fix logging during test failure
  tests/tests_suite_test.go
Labels: dco-signoff: yes, lgtm, approved, release-note-none, size/M

#516 Makefile: Enforce allowed go version
  Makefile
  go.mod
  hack/check-go-version.sh
  hack/check.sh
Labels: dco-signoff: yes, lgtm, approved, release-note-none, size/M
